apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: silicon-pod-operator-resources
      namespace: openshift-marketplace
    data:
      clusterServiceVersions: |
        - apiVersion: operators.coreos.com/v1alpha1
          kind: ClusterServiceVersion
          metadata:
            annotations:
              alm-examples: '[{"apiVersion":"app.siliconpod.com/v1alpha1","kind":"SiliconPod","metadata":{"name":"example-siliconpod"},"spec":{"size":3}}]'
              capabilities: Basic Install
              categories: Monitoring
            name: silicon-pod-operator.v0.0.1
            namespace: placeholder
          spec:
            apiservicedefinitions: {}
            description: Placeholder description
            displayName: Silicon Pod Operator
            install:
              spec:
                deployments:
                - name: silicon-pod-operator
                  spec:
                    replicas: 1
                    selector:
                      matchLabels:
                        name: silicon-pod-operator
                    strategy: {}
                    template:
                      metadata:
                        labels:
                          name: silicon-pod-operator
                      spec:
                        containers:
                        - command:
                          - silicon-pod-operator
                          env:
                          - name: WATCH_NAMESPACE
                            valueFrom:
                              fieldRef:
                                fieldPath: metadata.annotations['olm.targetNamespaces']
                          - name: POD_NAME
                            valueFrom:
                              fieldRef:
                                fieldPath: metadata.name
                          - name: OPERATOR_NAME
                            value: silicon-pod-operator
                          image: quay.io/aneeshkp/silicon-pod-operator:latest
                          imagePullPolicy: Always
                          name: silicon-pod-operator
                          resources: {}
                        serviceAccountName: silicon-pod-operator
                permissions:
                - rules:
                  - apiGroups:
                    - ""
                    resources:
                    - pods
                    - services
                    - services/finalizers
                    - endpoints
                    - persistentvolumeclaims
                    - events
                    - configmaps
                    - secrets
                    verbs:
                    - '*'
                  - apiGroups:
                    - apps
                    resources:
                    - deployments
                    - daemonsets
                    - replicasets
                    - statefulsets
                    verbs:
                    - '*'
                  - apiGroups:
                    - monitoring.coreos.com
                    resources:
                    - servicemonitors
                    verbs:
                    - get
                    - create
                  - apiGroups:
                    - apps
                    resourceNames:
                    - silicon-pod-operator
                    resources:
                    - deployments/finalizers
                    verbs:
                    - update
                  - apiGroups:
                    - ""
                    resources:
                    - pods
                    verbs:
                    - get
                  - apiGroups:
                    - apps
                    resources:
                    - replicasets
                    verbs:
                    - get
                  - apiGroups:
                    - app.siliconpod.com
                    resources:
                    - '*'
                    verbs:
                    - '*'
                  serviceAccountName: silicon-pod-operator
              strategy: deployment
            installModes:
            - supported: true
              type: OwnNamespace
            - supported: true
              type: SingleNamespace
            - supported: false
              type: MultiNamespace
            - supported: true
              type: AllNamespaces
            maturity: alpha
            provider: {}
            version: 0.0.1
          
            customresourcedefinitions:
              owned:
                - kind: SiliconPod
                  name: siliconpods.app.siliconpod.com
                  version: v1alpha1
                  displayName: SiliconPod
                  description: SiliconPod Deployment with the Operator  
      customResourceDefinitions: |
        - apiVersion: apiextensions.k8s.io/v1beta1
          kind: CustomResourceDefinition
          metadata:
            name: siliconpods.app.siliconpod.com
          spec:
            group: app.siliconpod.com
            names:
              kind: SiliconPod
              listKind: SiliconPodList
              plural: siliconpods
              singular: siliconpod
            scope: Namespaced
            subresources:
              status: {}
            validation:
              openAPIV3Schema:
                properties:
                  apiVersion:
                    description: 'APIVersion defines the versioned schema of this representation
                      of an object. Servers should convert recognized schemas to the latest
                      internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
                    type: string
                  kind:
                    description: 'Kind is a string value representing the REST resource this
                      object represents. Servers may infer this from the endpoint the client
                      submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                    type: string
                  metadata:
                    type: object
                  spec:
                    properties:
                      size:
                        description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                          Important: Run "operator-sdk generate k8s" to regenerate code after
                          modifying this file Add custom validation using kubebuilder tags:
                          https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                        format: int32
                        type: integer
                    required:
                    - size
                    type: object
                  status:
                    properties:
                      phase:
                        description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                          of cluster Important: Run "operator-sdk generate k8s" to regenerate
                          code after modifying this file Add custom validation using kubebuilder
                          tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
                        type: string
                      revNumber:
                        type: string
                    type: object
            version: v1alpha1
            versions:
            - name: v1alpha1
              served: true
              storage: true
      packages: >
        - channels:
          - currentCSV: silicon-pod-operator.v0.0.1
            name: alpha
          defaultChannel: alpha
          packageName: silicon-pod-operator

  - apiVersion: operators.coreos.com/v1alpha1
    kind: CatalogSource
    metadata:
      name: silicon-pod-operator-resources
      namespace: openshift-marketplace
    spec:
      configMap: silicon-pod-operator-resources
      displayName: Silicon Pod Operators
      publisher: Red Hat
      sourceType: internal
    status:
      configMapReference:
        name: silicon-pod-operator-resources
        namespace: openshift-marketplace
