apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # TODO this should be a clusterrole
  name: prometheus-k8s
  namespace: openshift-silicon-pod
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
